# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gypsy Moths
email: gypsymothshull@gmail.com
description: Hull & East Yorkshire Wedding and Events Band.

baseurl: "" # the subpath of your site, e.g. /blog
url: "gypsymothshull.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here

facebook_username: gypsymothshull


# Build settings
markdown: kramdown
